config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'home/index'
  devise_for :users
  # devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  resources :project_bugs
  resources :projects
  root to: "home#index"
  post 'assign_bug/:bug_id', to: 'project_bugs#assign_bug', as: :assign_bug

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project_bug.rb
class ProjectBug < ApplicationRecord
  belongs_to :project
  has_many :user_bugs
  has_many :users, through: :user_bugs
  has_one_attached :screenshot
  validates :title, uniqueness: true
  # validates :correct_image_type
  # private
  # def correct_image_type
  #   if screenshot.attached? && !screenshot.content_type.in?(%w(screenshot/gif,screenshot/png))
  #     errors.add(:screenshot,'Must be a Gif and Png')
  #   end
  # end
end

app/controllers/project_bugs_controller.rb
class ProjectBugsController < ApplicationController
  before_action :set_project_bug, only: %i[ show edit update destroy ]

  # GET /project_bugs or /project_bugs.json
  def index
    p1=Project.find_by(id: params[:project_id])
    @project_bugs = p1.project_bugs
  end
  # GET /project_bugs/1 or /project_bugs/1.json
  def show
    if @project_bug.assigned_id != nil
    @developer = User.find_by(id: @project_bug.assigned_id)
    end
  end
  # GET /project_bugs/new
  def new
    @project_bug = ProjectBug.new
  end

  # GET /project_bugs/1/edit
  def edit
  end
  # POST /project_bugs or /project_bugs.json
  def create
    @project = Project.find(params[:project_id])
    @project_bug=@project.project_bugs.create(project_bug_params)
    if @project_bug.errors.full_messages[0].present?
      redirect_to request.referer,flash: {error: @project_bug.errors.full_messages[0]}
    else
      redirect_to @project_bug
    end
    # p1=ProjectBug.find_by(id: params[:project_bug_id])
    # @project_bug = current_user.project_bugs.create(p1)
    # respond_to do |format|
    #     format.html { redirect_to @project_bug, notice: "Project bug was successfully created." }
    #     format.json { render :show, status: :created, location: @project_bug }
    # end
  end
  # PATCH/PUT /project_bugs/1 or /project_bugs/1.json
  def update
    respond_to do |format|

      if project_bug_params[:status] =="started"
        @project_bug.assigned_id = current_user.id

      end
      if @project_bug.update(project_bug_params)
        format.html { redirect_to @project_bug, notice: "Project bug was successfully updated." }
        format.json { render :show, status: :ok, location: @project_bug }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project_bug.errors, status: :unprocessable_entity }
      end
    end
  end
  def assign_bug
  end

  # DELETE /project_bugs/1 or /project_bugs/1.json
  def destroy
    @project_bug.destroy
    respond_to do |format|
      format.html { redirect_to project_bugs_url(project_id: @project_bug.project.id), notice: "Project bug was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_bug
      @project_bug = ProjectBug.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_bug_params
      params.require(:project_bug).permit(:title, :deadline, :project_id, :description, :status, :bug_type, :screenshot)
    end
end

app/helpers/project_bugs_helper.rb
module ProjectBugsHelper
end

app/views/project_bugs/_form.html.erb
<%=link_to "Back to Bugs", project_bugs_path(project_id: params[:project_id]),class: 'btn btn-success'%>


<%#= form_with(model: project_bug) do |form| %>
  <%#= hidden_field_tag :project_id, params[:project_id]%>
  <%# if flash[:error].present? %>
<!--    <div id="error_explanation">-->
<!--      <ul>-->
<!--          <li><%#= flash[:error]%></li>-->
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div style="background-color: lightblue; height: auto; width: auto">-->
<!--  <div class="field">-->
    <%#= form.label :title %>
    <%#= form.text_field :title %>
<!--  </div>-->
<!--  <div class="field">-->
    <%#= form.label :deadline %>
    <%#= form.date_select :deadline %>
<!--  </div>-->
<!--  <div class="field">-->
    <%#= form.label :screenshot %>
    <%#= form.file_field :screenshot %>
<!--  </div>-->
<!--  <div class="field">-->
    <%#= form.label :description %>
    <%#= form.text_area :description %>
<!--  </div>-->
<!--  <div class="field">-->
    <%#= form.label "Type" %>
    <%#=form.select(:bug_type, options_for_select([['bug', 'bug'], ['feature','feature']])) %>
<!--  </div>-->
  <%#= form.hidden_field :status, :value => "new" %>

<!--  <div class="field">-->
    <%#= form.label :type %>
    <%#= form.text_field :type %>
<!--  </div>-->
<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<!--  </div>-->
<%# end %>






<div style="background-color: lightblue" class="container m-5 p-5 justify-content-center" id="signUp">
  <div class="signup-form">
    <div class="col-xs-8 col-xs-offset-4">
    </div>

    <%= form_with(model: project_bug) do |form| %>
      <%= hidden_field_tag :project_id, params[:project_id]%>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <ul>
            <li><%= flash[:error]%></li>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= form.text_field :title, class:"form-control", required:"required",placeholder:"Title"%>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :deadline, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= form.date_select :deadline, class:"form-control"%>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :screenshot, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= form.file_field :screenshot, class:"form-control"%>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :description, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%= form.text_field :description, class:"form-control",required:"required",placeholder:"Description"%>
        </div>
      </div>



      <div class="form-group">
        <%= form.label :bug_type, class:"control-label col-xs-4" %>
        <div class="col-xs-8">
          <%=form.select(:bug_type, options_for_select([['bug', 'bug'], ['feature','feature']])) %>
        </div>
      </div>
      <%= form.hidden_field :status, :value => "new" %>
      <div class="actions">
        <%= form.submit %>
      </div>
      </div>
    <% end %>

<!--      <div class="form-group">-->
        <%#= f.label :password, class:"control-label col-xs-4" %>
        <%# if @minimum_password_length %>
<!--          <em>(<%#= @minimum_password_length %> characters minimum)</em>-->
<!--        <%# end %><br />-->
<!--        <div class="col-xs-8">-->
          <%#= f.password_field :password, class:"form-control", required:"required",autocomplete: "new-password", placeholder:"Enter password"%>
<!--        </div>-->
<!--      </div>-->
<!--      <div class="form-group">-->
        <%#= f.label :password_confirmation, class:"control-label col-xs-4" %>
<!--        <div class="col-xs-8">-->
          <%#= f.password_field :password_confirmation, class:"form-control", required:"required", autocomplete: "new-password", placeholder:"Enter password again"%>
<!--        </div>-->
<!--      </div>-->
<!--      <div class="form-group">-->
        <%#= f.submit "Sign up" , class: "btn btn-success"%>
<!--      </div>-->
    <%# end %>
    <%#= render "devise/shared/links" %>
  </div>
</div>

app/views/project_bugs/edit.html.erb
<h1>Editing Project Bug</h1>

<%= render 'form', project_bug: @project_bug %>

<!--<%#= link_to 'Show', @project_bug %> |-->
<%#= link_to 'Back', project_bugs_path %>

app/views/project_bugs/index.html.erb
<!--<h1> Project's bugs</h1>-->
<%# @project_bugs.each do |bugs| %>
<!--    <div class="card" style="width: 18rem;">-->
<!--      <img class="card-img-top" src="..." alt="Card image cap">-->
<!--      <div class="card-body">-->
<!--        <h5 class="card-title">Card title</h5>-->
<!--        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--      </div>-->
<!--      <ul class="list-group list-group-flush">-->
<!--        <li class="list-group-item">Cras justo odio</li>-->
<!--        <li class="list-group-item">Dapibus ac facilisis in</li>-->
<!--        <li class="list-group-item">Vestibulum at eros</li>-->
<!--      </ul>-->
<!--      <div class="card-body">-->
        <%#= link_to bugs.title, project_bug_path(bugs.id), class: "card-link"%>
<!--      </div>-->
<!--    </div>-->
<%# end %>
<%=link_to "Create New Bug", new_project_bug_path(project_id: params[:project_id]),class: 'btn btn-success'%>
<div class="container mt-5">
  <% if @project_bugs.any? %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="list-group">
          <div class="list-group-item list-group-item-action active">
            Bugs :
          </div>
          <% @project_bugs.each do |bugs| %>
            <div class="list-group-item list-group-item-action">
              <!--
   <span>Project Name :   <%#= link_to project.name,project_bugs_path(project_id: project.id) %></span>-->


              Bug Title: <%=link_to bugs.title, project_bug_path(bugs.id)%>
              <%#if current_user.user_type == "qa" %>
              <%#=link_to "Create Bug", new_project_bug_path(project_id: project)%>
              <%#end %>
              <!--              Project name : <%#=link_to project.name, project_path(project)%>-->
            </div>
          <%end %>
        </div>
      </div>
  <% else %>
    <p>No BUGS added by QA</p>
  <%end %>
  </div>
</div>

app/views/project_bugs/new.html.erb
<h1> Create New Project Bug</h1>

<%= render 'form', project_bug: @project_bug %>

<%#= link_to 'Back', project_bugs_path %>

app/views/project_bugs/show.html.erb
<p id="notice"><%= notice %></p>
<%=link_to "Back to Bugs", project_bugs_path(project_id: @project_bug.project.id),class: 'btn btn-success'%>
<p>
  <strong>Title:</strong>
  <%= @project_bug.title %>
</p>
<p>
  <strong>Deadline:</strong>
  <%= @project_bug.deadline %>
</p>
<strong>Bug Image:</strong>
<div >
  <% if @project_bug.screenshot.attached? %>
<%=image_tag(@project_bug.screenshot,  size: "200x200") %>
    <% end %>
</div>
<p>
  <strong>Description:</strong>
  <%= @project_bug.description %>
</p>
<p>
  <strong>Bug Type:</strong>
  <%= @project_bug.bug_type %>
</p>
<p>
  <strong>Status:</strong>
  <%if current_user.user_type == "qa"%>
    <%= @project_bug.status %>
    <%if @project_bug.status !="new" %>
      <br>
    <strong>Assigned To:</strong>
    <%=@developer.name%>
      <%end %>
    <%# %>
  <%# @project_bug.status == "new"%>

    <%else %>
    <%= @project_bug.status %>
  <% if (@project_bug.assigned_id && current_user.id == @project_bug.assigned_id) || @project_bug.status =='new'%>
<%= form_for(@project_bug, url: project_bug_path(@project_bug), html: {method: :patch}) do |f| %>
    <%= f.label :status%>
    <% if @project_bug.bug_type == 'feature' %>
      <%= f.select :status, ['new', 'started', 'complete']%>
    <% else %>
      <%= f.select :status, ['new', 'started', 'resolved']%>
    <% end %>
        <%if @project_bug.status == 'new' %>
    <%= f.submit "Assign Me" ,class:"btn btn-success"%>
          <%else %>
          <%= f.submit "save" ,class:"btn btn-success"%>
          <%end %>
  <% end %>
    <%end %>
    <%if @project_bug.assigned_id !=nil%>
      <p>
    <strong>Assigned To:</strong>
    <%=@developer.name%>
  </p>
<%end %>
    <%end %>
  <%# else %>
<!--  status : <%#= @bug.status %>-->
  <%#end %>
</p>

<%if current_user.user_type == "qa" %>
<%= link_to 'Edit', edit_project_bug_path(project_id: @project_bug.project.id),class:"btn btn-success "  %>
<%end %>
<%#= link_to 'Back', project_bugs_path %>