config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'home/index'
  devise_for :users
  # devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  resources :project_bugs
  resources :projects
  root to: "home#index"
  post 'assign_bug/:bug_id', to: 'project_bugs#assign_bug', as: :assign_bug

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_bugs, dependent: :destroy
  has_many :user_projects
  has_many :users,through: :user_projects, dependent: :delete_all
    # validates :name ,presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    respond_to do |format|
      if (@project = current_user.projects.create(project_params))
        format.html { redirect_to projects_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, user_ids: [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div style=" margin-left:50px; height: 500px; width: 1000px; background-color: lightblue; text-align: center" >
<br>
  <br>
  <br>
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<h1>Add Developer</h1>

  <% User.where(user_type: "developer").each do |user|%>
        <%= label_tag user.email,nil%>
        <%= form.check_box :user_ids, { multiple: true }, user.id, false %>
      <br>
  <%end %>
    <h1>Add QA</h1>
    <% User.where(user_type: "qa").each do |user|%>
      <%= label_tag user.email, nil%>
      <%= form.check_box :user_ids, { multiple: true }, user.id, false %>
    <%end %>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<%= render 'form', project: @project %>
<!--<%#= link_to 'Show', @project %> |-->
<%#= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->

    <%# @projects.each do |project| %>
<!--  <div class="card" style="width: 18rem;">-->
<!--    <img class="card-img-top" src="..." alt="Card image cap">-->
<!--    <div class="card-body">-->
<!--      <h5 class="card-title">Card title</h5>-->
<!--      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
<!--    </div>-->
<!--    <div class="card-body">-->

<!--    <span class="card-link"><%#= link_to project.name,project_bugs_path(project_id: project.id) %></span>-->
      <%#if current_user.user_type == "QA" %>
      <%#=link_to "Create Bug", new_project_bug_path(project_id: project)%>
        <%#end %>
        <%#= link_to 'Show', project %>
        <%#= link_to 'Edit', edit_project_path(project) %>
        <%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
<!--    </div>-->
<!--  </div>-->
<%#end %>
<%#= link_to 'New Project', new_project_path %>

















<div class="container mt-5">
  <% if @projects.any? %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="list-group">
          <div class="list-group-item list-group-item-action active">
            Projects
          </div>
          <% @projects.each do |project| %>
            <div class="list-group-item list-group-item-action">
<!--
   <span>Project Name :   <%#= link_to project.name,project_bugs_path(project_id: project.id) %></span>-->
              Project name : <%=link_to project.name, project_path(project)%>
<!--              Project name : <%#=link_to project.name, project_path(project)%>-->
            </div>
          <%end %>
        </div>
      </div>
  <% else %>
    <p>No projects added by manager</p>
  <%end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%#= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="container m-5 p-2">
  <div class="card text-dark bg-light m-3" style="max-width: 18rem;">
    <div class="card-header">Project title : <%= @project.name %></div>
    <div class="text-center">
      <% if @project.users.empty? %>
        <h3>No Users</h3>
      <% else %>
        <h3>Users</h3>
        </div>
        <% @project.users.each do |user| %>
          <div class="card-body">
          <h5 class="card-title">name : <%= user.name %></h5>
            <p class="card-text">type : <%= user.user_type %></p>
          </div>
        <% end %>
      <% end %>
      <%if current_user.user_type == "developer" %>
        <%=link_to "Show Bugs", project_bugs_path(project_id: @project.id),class: 'btn btn-success'%>
      <%end %>
      <%if current_user.user_type == "qa" %>
        <%=link_to "Create Bug", new_project_bug_path(project_id: @project.id),class: 'btn btn-secondary'%>
        <%=link_to "Show Bugs", project_bugs_path(project_id: @project.id),class: 'btn btn-success'%>
      <%end %>
      <% if current_user.user_type == 'manager' %>
        <%= link_to 'Edit project', edit_project_path(@project), class: 'btn btn-success' %>
        <%= link_to 'Delete project', project_path(@project), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure" } %>
      <% end %>
      </div>
</div>