config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'home/index'
  devise_for :users
  # devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  resources :project_bugs
  resources :projects
  root to: "home#index"
  post 'assign_bug/:bug_id', to: 'project_bugs#assign_bug', as: :assign_bug

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Bug Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <%if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out ', destroy_user_session_path, method: :delete,class: "nav-link"%>
        </li>
        <% if current_user.user_type == 'manager' %>
          <li class="nav-item">
            <%= link_to 'create project', new_project_path ,class: "nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to 'Projects',projects_path,class: "nav-link"%>
          </li>
        <%end %>
        <% if current_user.user_type == "developer"%>
          <li class="nav-item">
            <%= link_to 'View Project', projects_path ,class: "nav-link"%>
          </li>
        <%end %>
        <% if current_user.user_type == "qa"%>
<!--          <li class="nav-item">-->
            <%= link_to 'Projects',projects_path,class: "nav-link"%>
<!--          </li>-->
        <%end %>
          <li class="nav-item">
            <%= link_to current_user.name,user_path(current_user),class: "nav-link"%>
<!--            <a class="nav-link" href="#"><%#=current_user.name%></a>-->
          </li>
      <%else%>
      <li class="nav-item">
        <%= link_to 'Sign in ', new_user_session_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Register', new_user_registration_path ,class: "nav-link"%>
      </li>
      <%end %>
    </ul>
  </div>
</nav>

<%# if user_signed_in? %>
  <%# if current_user.user_type == 'Manager' %>
    <%#= link_to 'create project', new_project_path%>
  <%#end %>

  <%# if current_user.user_type == "developer" %>
<!--    <h1>All projects</h1>-->

    <%# current_user.projects.each do |project|%>

      <%#= link_to project.name,project_bugs_path(project_id: project.id)%>
      <br>
    <%#end %>
  <%#end %>

  <%#= link_to 'sign out ', destroy_user_session_path, method: :delete%>
<%#else %>
  <%#= link_to 'Register', new_user_registration_path %>
  <%#= link_to 'Sign in ', new_user_session_path %>
<%#end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugzillaNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
  <%#flash.each do |name, msg| %>
<!--  <div class="alert alert-<%#=name %>"> <%#=msg %></div>-->
  <%# end %>
  <%=render 'layouts/header' %>
  <%if notice.present? %>
    <p class="notice"><%= notice %></p>
  <%end %>
  <%if alert.present? %>
    <p class="alert"><%= alert %></p>
  <%end %>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>